targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        options:
          auto_register: true
          # Generate for the following environments
          generate_for:
            - lib/core/di/injection.dart